# Generated by Django 5.1.4 on 2025-01-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recepie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
